name: apex
description: A Finance App for Smart Pay.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  modal_progress_hud_nsn: ^0.2.1
  loading_animation_widget: ^1.2.0+1
  font_awesome_flutter: ^10.1.0
  smooth_page_indicator: ^1.0.0+2
  http: ^0.13.4
  flutter_otp_text_field: ^1.0.1
  country_picker: ^2.0.15
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/illustration.png
    - assets/images/device.png
    - assets/images/illustration_two.png
    - assets/images/device_two.png
    - assets/images/google.png
    - assets/images/password_lock.png
    - assets/images/pin_created.png
    - assets/images/diamond.png

  fonts:
    - family: SFProDisplay
      fonts:
       - asset: assets/fonts/SFProDisplay-Regular.ttf
